/* -*- C -*- */
static const char MOO_PY [] = ""
"\"\"\" moo module \"\"\"\n"
"from gi.repository import GObject as _gobject\n"
"\n"
"import _moo\n"
"from _moo import *\n"
"\n"
"try:\n"
"    _ = gettext\n"
"except NameError:\n"
"    _ = lambda s: s\n"
"\n"
"try:\n"
"    D_ = dgettext\n"
"except NameError:\n"
"    D_ = lambda s: s\n"
"\n"
"def N_(string):\n"
"    return string\n"
"\n"
"class _PluginWontLoad(Exception):\n"
"    def __repr__(self):\n"
"        return 'PluginWontLoad'\n"
"\n"
"def _cancel_plugin_loading():\n"
"    raise _PluginWontLoad()\n"
"\n"
"class _ActionFactory(object):\n"
"    def __init__(self, action_id, **kwargs):\n"
"        object.__init__(self)\n"
"        self.id = action_id\n"
"        self.props = {}\n"
"        self.fake_props = {}\n"
"        for key in list(kwargs.keys()):\n"
"            if key in [\"callback\"]:\n"
"                self.fake_props[key] = kwargs[key]\n"
"            elif kwargs[key] is not None or key not in [\"stock_id\"]:\n"
"                self.props[key] = kwargs[key]\n"
"\n"
"    def __call__(self, window):\n"
"        self.window = window\n"
"        action = _gobject.new(Action, name=self.id, **self.props)\n"
"        self.set_fake_props(action)\n"
"        return action\n"
"\n"
"    def set_fake_props(self, action):\n"
"        def _activate(action, callback, window):\n"
"            callback(window)\n"
"        for key in list(self.fake_props.keys()):\n"
"            if key == \"callback\":\n"
"                action.connect(\"activate\", _activate, self.fake_props[key], self.window)\n"
"            else:\n"
"                raise ValueError(\"unknown property \" + key)\n"
"\n"
"    def set_props(self, action):\n"
"        for key in list(self.props.keys()):\n"
"            action.set_property(key, self.props[key])\n"
"\n"
"def window_class_add_action(klass, action_id, group=None, **kwargs):\n"
"    if \"factory\" in kwargs:\n"
"        _moo.window_class_add_action(klass, action_id, group, kwargs[\"factory\"])\n"
"    else:\n"
"        _moo.window_class_add_action(klass, action_id, group, _ActionFactory(action_id, **kwargs))\n"
;
