/* -*- C -*- */
static const char MOO_PY [] = ""
"#\n"
"#  moo-mod.py\n"
"#\n"
"#  Copyright (C) 2004-2010 by Yevgen Muntyan <emuntyan@users.sourceforge.net>\n"
"#\n"
"#  This file is part of medit.  medit is free software; you can\n"
"#  redistribute it and/or modify it under the terms of the\n"
"#  GNU Lesser General Public License as published by the\n"
"#  Free Software Foundation; either version 2.1 of the License,\n"
"#  or (at your option) any later version.\n"
"#\n"
"#  You should have received a copy of the GNU Lesser General Public\n"
"#  License along with medit.  If not, see <http://www.gnu.org/licenses/>.\n"
"#\n"
"\n"
"\"\"\" moo module \"\"\"\n"
"\n"
"# Python 3 + PyGObject imports\n"
"import gi\n"
"gi.require_version('Gtk', '3.0')\n"
"from gi.repository import Gtk as _gtk\n"
"from gi.repository import GObject as _gobject\n"
"\n"
"# Import the native _moo module (assuming it's been updated for Python 3)\n"
"import _moo\n"
"from _moo import *\n"
"\n"
"# note, these aren't standard gettext functions\n"
"_ = gettext\n"
"D_ = dgettext\n"
"\n"
"def N_(string):\n"
"    return string\n"
"\n"
"class _PluginWontLoad(Exception):\n"
"    def __repr__(self):\n"
"        return 'PluginWontLoad'\n"
"\n"
"def _cancel_plugin_loading():\n"
"    raise _PluginWontLoad()\n"
"\n"
"class _ActionFactory(object):\n"
"    def __init__(self, action_id, **kwargs):\n"
"        object.__init__(self)\n"
"        self.id = action_id\n"
"\n"
"        self.props = {}\n"
"        self.fake_props = {}\n"
"\n"
"        # Python 3: dict.keys() returns a view, convert to list for compatibility\n"
"        for key in list(kwargs.keys()):\n"
"            if key in [\"callback\"]:\n"
"                self.fake_props[key] = kwargs[key]\n"
"            elif kwargs[key] is not None or key not in [\"stock_id\"]:\n"
"                self.props[key] = kwargs[key]\n"
"\n"
"    def __call__(self, window):\n"
"        self.window = window\n"
"        # PyGObject: Use GObject.new() instead of _gobject.new()\n"
"        action = _gobject.new(Action, name=self.id, **self.props)\n"
"        self.set_fake_props(action)\n"
"        return action\n"
"\n"
"    def set_fake_props(self, action):\n"
"        def _activate(action, callback, window):\n"
"            callback(window)\n"
"\n"
"        # Python 3: dict.keys() returns a view, convert to list\n"
"        for key in list(self.fake_props.keys()):\n"
"            if key == \"callback\":\n"
"                action.connect(\"activate\", _activate, self.fake_props[key], self.window)\n"
"            else:\n"
"                raise ValueError(\"unknown property \" + key)\n"
"\n"
"    def set_props(self, action):\n"
"        # Python 3: dict.keys() returns a view, convert to list\n"
"        for key in list(self.props.keys()):\n"
"            action.set_property(key, self.props[key])\n"
"\n"
"def window_class_add_action(klass, action_id, group=None, **kwargs):\n"
"    if \"factory\" in kwargs:\n"
"        _moo.window_class_add_action(klass, action_id, group, kwargs[\"factory\"])\n"
"    else:\n"
"        _moo.window_class_add_action(klass, action_id, group, _ActionFactory(action_id, **kwargs))\n"
;
