# cmake/MooOS.cmake
# Equivalent of MOO_AC_CHECK_OS and MOO_LT_LIB_M from moo-os.m4

# ── Detect OS ────────────────────────────────────────────────────────────────
set(MOO_OS_WIN32  FALSE)
set(MOO_OS_CYGWIN FALSE)
set(MOO_OS_DARWIN FALSE)
set(MOO_OS_FREEBSD FALSE)
set(MOO_OS_LINUX  FALSE)
set(MOO_OS_UNIX   FALSE)
set(MOO_OS_BSD    FALSE)
set(MOO_OS_FDO    FALSE)   # freedesktop.org (catch-all for Linux/Unix with pkg-config etc.)
set(MOO_OS_MINGW  FALSE)

if(WIN32)
    if(MINGW)
        set(MOO_OS_WIN32  TRUE)
        set(MOO_OS_MINGW  TRUE)
        set(MOO_OS_NAME   "Win32")
    elseif(CYGWIN)
        set(MOO_OS_CYGWIN TRUE)
        set(MOO_OS_NAME   "CygWin")
    else()
        set(MOO_OS_WIN32  TRUE)
        set(MOO_OS_NAME   "Win32")
    endif()
elseif(APPLE)
    set(MOO_OS_DARWIN TRUE)
    set(MOO_OS_BSD    TRUE)
    set(MOO_OS_UNIX   TRUE)
    set(MOO_OS_NAME   "Darwin")
elseif(CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
    set(MOO_OS_FREEBSD TRUE)
    set(MOO_OS_BSD     TRUE)
    set(MOO_OS_UNIX    TRUE)
    set(MOO_OS_NAME    "FreeBSD")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(MOO_OS_LINUX TRUE)
    set(MOO_OS_UNIX  TRUE)
    set(MOO_OS_FDO   TRUE)
    set(MOO_OS_NAME  "Linux")
else()
    set(MOO_OS_UNIX TRUE)
    set(MOO_OS_NAME "Unix")
endif()

# Any non-Windows is also Unix (mirrors: if ! WIN32 then UNIX=true)
if(NOT MOO_OS_WIN32)
    set(MOO_OS_UNIX TRUE)
endif()

message(STATUS "Detected OS: ${MOO_OS_NAME}")

# ── Math library (MOO_LT_LIB_M) ─────────────────────────────────────────────
# Platforms that don't need libm:
if(APPLE OR CYGWIN OR WIN32)
    set(MOO_LIBM "")
else()
    find_library(MOO_LIBM_LIB m)
    if(MOO_LIBM_LIB)
        set(MOO_LIBM "${MOO_LIBM_LIB}")
    else()
        set(MOO_LIBM "")
    endif()
endif()
